spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.sql.init.platform=h2
spring.datasource.url=jdbc:h2:mem:hexagonal
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create-drop

brasilapi.cep.base-url=https://brasilapi.com.br
spring.cloud.openfeign.client.config.findAddressByZipCode.connect-timeout=3000
spring.cloud.openfeign.client.config.findAddressByZipCode.read-timeout=5000
spring.cloud.openfeign.client.config.brasilApiCep.connect-timeout=3000
spring.cloud.openfeign.client.config.brasilApiCep.read-timeout=5000
